/** 鉴权页标题 / 按钮文案 — 双端对齐 */

export const AUTH_TITLE_WELCOME_BACK = '欢迎回来'
export const AUTH_TITLE_LOGIN = '登录账户'
export const AUTH_NAV_LOGIN = '登录'
export const AUTH_NAV_CREATE_ACCOUNT = '创建账号'
/** PC 浏览器标题等短标签 */
export const AUTH_NAV_REGISTER = '注册'
export const AUTH_TITLE_REGISTER = '注册账户'
export const AUTH_TITLE_FORGOT = '忘记密码'
export const AUTH_TITLE_RECOVER = '找回密码'
export const AUTH_TITLE_RESET = '重置密码'
export const AUTH_TITLE_SET_NEW_PASSWORD = '设置新密码'
export const AUTH_TITLE_RESET_SUCCESS = '重置成功'
export const AUTH_TITLE_PASSWORD_RESET_DONE = '密码已重置'
export const AUTH_DESC_PASSWORD_RESET_DONE = '请用新密码登录账户'
export const AUTH_DESC_CODE_SENT = '验证码已发送至您的邮箱'

export const AUTH_CAPTCHA_ALT = '验证码'
export const AUTH_CAPTCHA_REFRESH_TITLE = '点击刷新验证码'
export const AUTH_FORGOT_LINK = '忘记密码？'

export const ACTION_SEND_CODE = '发送验证码'
export const ACTION_RESEND_CODE = '重新发送'
export const ACTION_SENDING = '发送中...'
export const ACTION_RESET_PASSWORD = '重置密码'
export const ACTION_RESETTING = '重置中...'
export const ACTION_LOGIN = '登录'
export const ACTION_REGISTER = '注册'
export const ACTION_UPDATING = '更新中...'
export const ACTION_UPDATE_INFO = '更新信息'
export const ACTION_LOGGING_IN = '登录中...'
export const ACTION_LOGIN_SPACED = '登 录'
export const AUTH_REGISTER_LINK = '注册新账户'
export const AUTH_SUB_FORGOT_EMAIL = '请输入注册邮箱，我们将发送验证码'
export const AUTH_SUB_PASSWORD_UPDATED = '密码已更新，请使用新密码登录'
export const AUTH_SUB_RECOVER_LINE1 = '别担心，我们帮你找回'
export const AUTH_SUB_RECOVER_LINE2 = '请验证您的身份信息'
export const AUTH_SUB_RESET_AFTER = '重置后请使用新密码登录'
export const AUTH_TITLE_PASSWORD_RESET_SUCCESS = '密码重置成功'
export const AUTH_TITLE_CREATE_ACCOUNT = '创建账户'
export const ACTION_REGISTERING = '注册中...'
export const ACTION_REGISTER_SPACED = '注 册'
export const AUTH_SEND_FAILED_CHECK_EMAIL = '发送失败，请检查邮箱地址'
export const AUTH_RESET_FAILED_RETRY = '重置失败，请重试'
export const AUTH_CODE_SENT_TO_PREFIX = '验证码已发送至 '
export const ACTION_LOGGING_IN_ELLIPSIS = '登录中…'
export const ACTION_REGISTERING_ELLIPSIS = '注册中…'
export const ACTION_SENDING_ELLIPSIS = '发送中…'
export const ACTION_RESETTING_ELLIPSIS = '重置中…'
export const AUTH_LOGIN_FAILED = '登录失败，请重试'
export const ACTION_CHANGE_PASSWORD = '修改密码'
export const AUTH_CHANGE_PASSWORD_FAILED = '修改密码失败'
export const AUTH_SAVE_PROFILE_FAILED = '保存失败，请检查网络或稍后重试'

export const AUTH_LOGIN_EXPIRED = '登录已过期'
export const AUTH_LOGIN_EXPIRED_REENTER = '登录已过期，请重新输入密码'
export const AUTH_ADD_NEW_ACCOUNT_LOGIN = '添加新账号登录'

/** email 的登录状态已失效，请重新登录 */
export function authLoginExpiredRelogin(email: string): string {
  return `${email} 的登录状态已失效，请重新登录`
}

export const AUTH_BRAND_TAGLINE = '财猫家庭记账 · 让每一笔都清晰可见'
export const AUTH_CAPTCHA_FETCH_FAILED = '获取验证码失败'
export const AUTH_LOGIN_CHECK_CREDENTIALS = '登录失败，请检查账号密码和验证码'
