/** 鉴权页标题 / 按钮文案 — 双端对齐 */

export const AUTH_TITLE_WELCOME_BACK = '欢迎回来'
export const AUTH_TITLE_LOGIN = '登录账户'
export const AUTH_TITLE_REGISTER = '注册账户'
export const AUTH_TITLE_FORGOT = '忘记密码'
export const AUTH_TITLE_RECOVER = '找回密码'
export const AUTH_TITLE_RESET = '重置密码'
export const AUTH_TITLE_SET_NEW_PASSWORD = '设置新密码'
export const AUTH_TITLE_RESET_SUCCESS = '重置成功'
export const AUTH_TITLE_PASSWORD_RESET_DONE = '密码已重置'
export const AUTH_DESC_PASSWORD_RESET_DONE = '请用新密码登录账户'
export const AUTH_DESC_CODE_SENT = '验证码已发送至您的邮箱'

export const AUTH_CAPTCHA_ALT = '验证码'
export const AUTH_CAPTCHA_REFRESH_TITLE = '点击刷新验证码'
export const AUTH_FORGOT_LINK = '忘记密码？'

export const ACTION_SEND_CODE = '发送验证码'
export const ACTION_RESEND_CODE = '重新发送'
export const ACTION_SENDING = '发送中...'
export const ACTION_RESET_PASSWORD = '重置密码'
export const ACTION_RESETTING = '重置中...'
export const ACTION_LOGIN = '登录'
export const ACTION_REGISTER = '注册'
export const ACTION_UPDATING = '更新中...'
export const ACTION_UPDATE_INFO = '更新信息'
export const ACTION_LOGGING_IN = '登录中...'
export const ACTION_LOGIN_SPACED = '登 录'
export const AUTH_REGISTER_LINK = '注册新账户'
