/** 表单/详情字段标签 — 双端对齐 */

export const FIELD_NAME = '名称'
export const FIELD_TYPE = '类型'
export const FIELD_AMOUNT = '金额'
export const FIELD_CATEGORY = '分类'
export const FIELD_DATE = '日期'
export const FIELD_BRAND = '品牌'
export const FIELD_NOTE = '备注'
export const FIELD_LOCATION = '位置'
export const FIELD_FREQUENCY = '频率'
export const FIELD_SORT = '排序'
export const FIELD_START_DATE = '开始日期'

/** 排序展示：第 N 位（sort_order 从 0 起） */
export function sortOrderLabel(sortOrder: number): string {
  return `第 ${Number(sortOrder) + 1} 位`
}
export const FIELD_MERCHANT = '商户'
export const FIELD_CYCLE = '周期'
export const FIELD_END_DATE = '结束日期'
export const FIELD_LAST_EXECUTED = '上次执行'
export const FIELD_NEXT_EXECUTED = '下次执行'
export const FIELD_CREATED_AT = '创建时间'
export const FIELD_UPDATED_AT = '更新时间'
export const FIELD_TEMPLATE = '模板'
export const FIELD_CATEGORY_ID = '分类 ID'
export const FIELD_TEMPLATE_NAME = '模板名称'
export const FIELD_LOCATION_INFO = '位置信息'
export const FIELD_DESCRIPTION = '描述'
export const FIELD_PLACE = '地点'
export const FIELD_COORDINATES = '坐标'
export const FIELD_BOOK_NAME = '账本名称'
export const FIELD_DESC_OPTIONAL = '描述（可选）'
export const FIELD_ICON = '图标'
export const FIELD_CUSTOM = '自定义'
export const FIELD_OWNER_EMAIL = '新拥有者邮箱'
export const FIELD_YOUR_PASSWORD = '您的密码'
export const FIELD_ADDRESS = '地址'
export const FIELD_MERCHANT_ID = '商户 ID'
export const FIELD_MERCHANT_NAME = '商户名称'
export const FIELD_BOOK_ID = '账本 ID'
export const FIELD_USERNAME = '用户名'
export const FIELD_EMAIL = '邮箱'
export const FIELD_CURRENT_PASSWORD = '当前密码'
export const FIELD_NEW_PASSWORD = '新密码'
export const FIELD_CONFIRM_NEW_PASSWORD = '确认新密码'
export const FIELD_INVITE_CODE = '邀请码'
export const FIELD_PROGRESS = '使用进度'
export const FIELD_SPENT = '已使用'
export const FIELD_BUDGET_AMOUNT = '预算'
export const FIELD_REMAINING = '剩余'
export const FIELD_STATUS = '状态'
export const FIELD_MONTH = '月份'
export const FIELD_EMAIL_ADDRESS = '邮箱地址'
export const FIELD_PASSWORD = '密码'
export const FIELD_CAPTCHA = '验证码'
export const FIELD_CONFIRM_PASSWORD = '确认密码'
export const FIELD_MEMBERS = '成员'
export const FIELD_TXN_COUNT = '交易笔数'
export const FIELD_OWNER_ID = '账主 ID'
export const FIELD_VIEW = '视图'
export const FIELD_MEMBER = '成员'
export const FIELD_END_DATE_OPTIONAL = '结束日期（可选）'
export const FIELD_MONTH_BALANCE = '本月结余'
export const FIELD_MONTH_INCOME = '本月收入'
export const FIELD_MONTH_EXPENSE = '本月支出'
export const FIELD_YEAR_INCOME = '年度总收入'
export const FIELD_YEAR_EXPENSE = '年度总支出'
export const FIELD_YEAR_BALANCE = '年度结余'
export const FIELD_BALANCE_RATE = '结余率'
