/** 表单校验 / placeholder 高频文案 */

export const FORM_NAME_REQUIRED = '请输入名称'
export const FORM_INVITE_CODE_REQUIRED = '请输入邀请码'
export const FORM_INVITE_CODE_MIN = '邀请码至少需要4位'
export const FORM_AMOUNT_INVALID = '请输入有效金额'
export const FORM_CATEGORY_REQUIRED = '请选择分类'
export const FORM_TEMPLATE_NAME_REQUIRED = '请输入模板名称'
export const FORM_EMAIL_REQUIRED = '请输入邮箱地址'
export const FORM_EMAIL_PASSWORD_REQUIRED = '请输入邮箱和密码'
export const FORM_CAPTCHA_REQUIRED = '请输入验证码'
export const FORM_PASSWORD_CURRENT = '请输入当前密码'
export const FORM_USERNAME_REQUIRED = '用户名不能为空'
export const FORM_BUDGET_NONE = '请至少设置一个分类的预算金额'
export const FORM_SELECT_PLACEHOLDER = '请选择'
export const FORM_PEER_EMAIL_PLACEHOLDER = '请输入对方的邮箱'
export const FORM_INVITE_CODE_PLACEHOLDER = '请输入邀请码'

export const FORM_BUDGET_NO_LAST_MONTH = '上月暂无预算可复制'
export const FORM_ALREADY_CURRENT_ACCOUNT = '当前已是该账号'
export const FORM_ALREADY_CURRENT_BOOK = '当前已是该账本'
export const FORM_PRIVACY_REQUIRED = '请先同意隐私协议'

export const FORM_OWNER_EMAIL_REQUIRED = '请输入新拥有者邮箱'
export const FORM_PASSWORD_VERIFY = '请输入密码验证'
export const FORM_DEACTIVATE_PASSWORD = '请输入密码以确认注销'

export const FORM_PASSWORD_MIN = (min = 6) => `密码长度至少为 ${min} 位`
export const FORM_PASSWORD_MIN_NEW = '新密码长度至少为 6 位'
export const FORM_PASSWORD_MISMATCH = '两次密码不一致'
export const FORM_PASSWORD_MISMATCH_NEW = '两次输入的新密码不一致'
export const FORM_PASSWORD_STRENGTH = '新密码必须同时包含大小写字母和数字'
export const FORM_PASSWORD_ALPHA_NUMERIC = '密码必须包含字母和数字'
export const FORM_EMAIL_EMPTY = '邮箱不能为空'
export const FORM_EMAIL_INVALID = '邮箱格式不正确'
export const FORM_BACK = '返回'
export const FORM_BACK_LOGIN = '返回登录'
export const FORM_PRIVACY_LOCATION = '请先同意隐私协议后使用定位'
export const FORM_LOCATION_REQUIRED = '请先选择位置'
export const FORM_LOCATION_UNAVAILABLE = '无法获取当前位置'
export const FORM_LOCATION_DENIED = '位置权限被拒绝，请在设置中开启'
export const FORM_LOCATION_TIMEOUT = '定位超时，请检查网络或到开阔处重试'
export const FORM_LOCATION_MANUAL_HINT = '，可手动搜索或点击地图选择'

export const FORM_CAPTCHA_PLACEHOLDER = '请输入验证码'
export const FORM_USERNAME_PLACEHOLDER = '请输入用户名'
export const FORM_EMAIL_PLACEHOLDER = '请输入邮箱'
export const FORM_PASSWORD_CONFIRM_NEW_PLACEHOLDER = '请再次输入新密码'
export const FORM_MEMBER_EMAIL_PLACEHOLDER = '请输入该成员的账号邮箱'

/** 高频 placeholder（记一笔 / 模板 / 分类 / 预算） */
export const FORM_AMOUNT_PLACEHOLDER = '0.00'
export const FORM_SELECT_CATEGORY = '选择分类'
export const FORM_SELECT_TYPE = '选择类型'
export const FORM_TEMPLATE_NAME_EXAMPLE = '如：公司食堂午餐'
export const FORM_NOTE_OPTIONAL = '添加备注（可选）'
export const FORM_CATEGORY_NAME_PLACEHOLDER = '输入分类名称'
export const FORM_BRAND_EXAMPLE = '例如：雅诗兰黛、苹果'
export const FORM_DESC_EXAMPLE = '例如：小棕瓶 50ml，给妈妈买的礼物'
export const FORM_PASSWORD_PLACEHOLDER = '输入密码'
export const FORM_PASSWORD_LOGIN_PLACEHOLDER = '输入登录密码'
export const FORM_TEMPLATE_SELECT = '选择模板快速记账'
export const FORM_BUDGET_AMOUNT_PLACEHOLDER = '预算金额'
export const FORM_SEARCH_TXN = '搜索描述/品牌...'
export const FORM_SEARCH_LOCATION = '搜索地址或商户名称...'
export const FORM_BOOK_NAME_EXAMPLE = '如：家庭账本'
export const FORM_BOOK_DESC_EXAMPLE = '简单介绍一下这个账本'
export const FORM_MEMBER_EMAIL_SHORT = '输入用户邮箱'
export const FORM_INVITE_CODE_EXAMPLE = '例如 A3F8K2'
export const FORM_PASSWORD_STRENGTH_HINT = '至少 6 位，含大小写 + 数字'

export const FORM_EMAIL_EXAMPLE = 'your@email.com'
export const FORM_NICKNAME_PLACEHOLDER = '您的昵称'
export const FORM_PASSWORD_MIN_SHORT = '至少6位'
export const FORM_PASSWORD_CONFIRM_PLACEHOLDER = '再次输入'
export const FORM_PASSWORD_MIN_ALPHA_NUM = '至少6位，含字母和数字'
export const FORM_REGISTERED_EMAIL_PLACEHOLDER = '注册时使用的邮箱'
export const FORM_CAPTCHA_DIGITS_PLACEHOLDER = '6位数字'
export const FORM_PASSWORD_VERIFY_IDENTITY = '输入密码以验证身份'

export const FORM_MIN_AMOUNT = '最小金额'
export const FORM_MAX_AMOUNT = '最大金额'
export const FORM_SELECT_MONTH = '选择月份'
export const FORM_SELECT_FREQUENCY = '选择频率'
export const FORM_ADMIN_PASSWORD_PLACEHOLDER = '输入您的管理员密码'
export const FORM_SEARCH_MERCHANT = '搜索商户名称 / 地址'
